services:
  # Change-Detection - Webpage Change Monitoring and Notification
  change-detection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: change-detection
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #  - "5000:5000"
    volumes:
      - $DOCKERDIR/appdata/change-detection:/config
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: /change-detection #optional
      # PLAYWRIGHT_DRIVER_URL: #optional
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.change-detection-rtr.entrypoints=websecure"
      - "traefik.http.routers.change-detection-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.change-detection-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.change-detection-rtr.service=change-detection-svc"
      - "traefik.http.services.change-detection-svc.loadbalancer.server.port=5000"