services:
  # Chromium - Web Browser
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined #optional
    restart: "unless-stopped"
    profiles: ["apps", "all"]
    shm_size: "1gb"
    networks:
      - t3_proxy
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    volumes:
      - $DOCKERDIR/appdata/chromium:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      # CHROME_CLI: https://www.deployarr.app/ #optional
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.chromium-rtr.entrypoints=websecure"
      - "traefik.http.routers.chromium-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.chromium-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.chromium-rtr.service=chromium-svc"
      - "traefik.http.services.chromium-svc.loadbalancer.server.port=3000"