services:
  # CyberChef - Encryption, encoding, compression and data analysis
  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - 8000:8000
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.cyberchef-rtr.entrypoints=websecure"
      - "traefik.http.routers.cyberchef-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.cyberchef-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.cyberchef-rtr.service=cyberchef-svc"
      - "traefik.http.services.cyberchef-svc.loadbalancer.server.port=8000"