services:
  # Jackett - Torrent proxy
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - t3_proxy
    ports:
      - "9117:9117"
    volumes:
      - $DOCKERDIR/appdata/jackett:/config
      - $DOWNLOADSDIR:/data/downloads
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jackett-rtr.entrypoints=websecure"
      - "traefik.http.routers.jackett-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.jackett-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.jackett-rtr.service=jackett-svc"
      - "traefik.http.services.jackett-svc.loadbalancer.server.port=9117"