services:
  # MQTTX Web - Browser-based MQTT WebSocket client
  mqttx-web:
    image: emqx/mqttx-web:latest
    container_name: mqttx-web
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
      - default
    # ports:
    #   - "80:80"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.mqttx-web-rtr.entrypoints=websecure"
      - "traefik.http.routers.mqttx-web-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.mqttx-web-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.mqttx-web-rtr.service=mqttx-web-svc"
      - "traefik.http.services.mqttx-web-svc.loadbalancer.server.port=80"