services:
  # Nextcloud - Content Collaboration
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
      - default
    # ports:
    #   - "8085:80"
    volumes:
      - $DOCKERDIR/appdata/nextcloud:/var/www/html
      - $NEXTCLOUD_FOLDER:/var/www/html/data
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/nextcloud_mariadb_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER_FILE: /run/secrets/nextcloud_mariadb_user
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: $REDIS_PASSWORD
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      NEXTCLOUD_TRUSTED_DOMAINS: SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1
    secrets:
      - nextcloud_mariadb_password
      - nextcloud_mariadb_user
      - nextcloud_admin_user
      - nextcloud_admin_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.nextcloud-rtr.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.nextcloud-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      # HTTP Services
      - "traefik.http.routers.nextcloud-rtr.service=nextcloud-svc"
      - "traefik.http.services.nextcloud-svc.loadbalancer.server.port=80"