services:
  # Node-RED - Programming for event-driven applications
  node-red:
    image: nodered/node-red
    container_name: node-red
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "1880:1880"
    volumes:
      - $DOCKERDIR/appdata/node-red:/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.node-red-rtr.entrypoints=websecure"
      - "traefik.http.routers.node-red-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.node-red-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.node-red-rtr.service=node-red-svc"
      - "traefik.http.services.node-red-svc.loadbalancer.server.port=1880"