services:
  # pgAdmin - PostgreSQL Administration
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
      - default
    # ports:
    #   - "$PGADMIN_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_ADMIN_PASSWORD
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.pgadmin-rtr.entrypoints=websecure"
      - "traefik.http.routers.pgadmin-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.pgadmin-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      # HTTP Services
      - "traefik.http.routers.pgadmin-rtr.service=pgadmin-svc"
      - "traefik.http.services.pgadmin-svc.loadbalancer.server.port=80"