services:
  # Piwigo - Photo Management
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "80:80"
    volumes:
      - $DOCKERDIR/appdata/piwigo/config:/config
      - $DOCKERDIR/appdata/piwigo/gallery:/gallery
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.piwigo-rtr.entrypoints=websecure"
      - "traefik.http.routers.piwigo-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.piwigo-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.piwigo-rtr.service=piwigo-svc"
      - "traefik.http.services.piwigo-svc.loadbalancer.server.port=80"