services:
  # The Lounge - Self-hosted web IRC client
  thelounge:
    image: lscr.io/linuxserver/thelounge:latest
    container_name: thelounge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - 9000:9000
    volumes:
      - $DOCKERDIR/appdata/thelounge:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.thelounge-rtr.entrypoints=websecure"
      - "traefik.http.routers.thelounge-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.thelounge-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.thelounge-rtr.service=thelounge-svc"
      - "traefik.http.services.thelounge-svc.loadbalancer.server.port=9000"