http:
  routers:
    APPNAME-PLACEHOLDER-rtr:
      rule: "Host(`APPNAME-PLACEHOLDER.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure
      middlewares:
        - CHAIN-PLACEHOLDER
      service: APPNAME-PLACEHOLDER-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    APPNAME-PLACEHOLDER-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: "APPNAME-PLACEHOLDER"
        servers:
          - url: "APP-URL-PLACEHOLDER"  # https://IP-ADDRESS:PORT
  serversTransports:
    APPNAME-PLACEHOLDER:
      insecureSkipVerify: true