# Replace APPNAME PLACEHOLDER with a name for your app (e.g. unifi), CHAIN PLACEHOLDER with one of the middleware chains (e.g. chain-no-auth, chain-authelia, chain-basic-auth, etc.), and APP-URL PLACEHOLDER with internal URL of the app (e.g. http://192.168.1.100:8080).
# For each app place the final yml file in docker/appdata/traefik2/rules folder.
http:
  routers:
    APPNAME-PLACEHOLDER-rtr:
      rule: "Host(`APPNAME-PLACEHOLDER.{{env "DOMAINNAME_1"}}`)" 
      entryPoints:
        - websecure
      middlewares:
        - CHAIN-PLACEHOLDER
      service: APPNAME-PLACEHOLDER-svc
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
  services:
    APPNAME-PLACEHOLDER-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: "APPNAME-PLACEHOLDER"
        servers:
          - url: "APP-URL-PLACEHOLDER"  # https://IP-ADDRESS:PORT
  serversTransports:
    APPNAME-PLACEHOLDER:
      insecureSkipVerify: true