services:
  # Airsonic Advanced - Music Server
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic-advanced
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    volumes:
      - $DOCKERDIR/appdata/airsonic/podcasts:/data/podcasts
      - $DOCKERDIR/appdata/airsonic/playlists:/data/playlists
      - $DOCKERDIR/appdata/airsonic/config:/config
      # - $MEDIADIR1:/data/media1
      # - $MEDIADIR2:/data/media2
      # - $MEDIADIR3:/data/media3
    ports:
      - "4040:4040"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      JAVA_OPTS: '-Dserver.forward-headers-strategy=native' # optional - if you use a reverse-proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.airsonic-advanced-rtr.entrypoints=websecure"
      - "traefik.http.routers.airsonic-advanced-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.airsonic-advanced-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.airsonic-advanced-rtr.service=airsonic-advanced-svc"
      - "traefik.http.services.airsonic-advanced-svc.loadbalancer.server.port=4040"