services:
  # CyberChef - Encryption, encoding, compression and data analysis
  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
      # - t3_proxy
    ports:
      - "$CYBERCHEF_PORT:8000"
    # DOCKER-LABELS-PLACEHOLDER
