services:
  # Dashy - Application Dashboard
  dashy:
    container_name: dashy
    image: lissy93/dashy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # ports:
    #   - $DASHY_PORT:8080
    volumes:
      - $DOCKERDIR/appdata/dashy/conf.yml:/app/public/conf.yml
      - $DOCKERDIR/appdata/dashy/item-icons:/app/public/item-icons
    environment:
      - NODE_ENV=production
      - UID=$PUID
      - GID=$PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dashy-rtr.entrypoints=websecure"
      - "traefik.http.routers.dashy-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.dashy-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      # HTTP Services
      - "traefik.http.routers.dashy-rtr.service=dashy-svc"
      - "traefik.http.services.dashy-svc.loadbalancer.server.port=8080"