services:
  # Kavita - Cross-platform Reading Server
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - t3_proxy
    # ports:
    #  - "$KAVITA_PORT:5000" 
    volumes:
      - $DOCKERDIR/appdata/kavita:/config
      - $BOOKSDIR:/data
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.kavita-rtr.entrypoints=websecure"
      - "traefik.http.routers.kavita-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.kavita-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.kavita-rtr.service=kavita-svc"
      - "traefik.http.services.kavita-svc.loadbalancer.server.port=5000"