services:
  # Maintainerr - Manage Plex Media
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #  - "6246:6246"
    user: $PUID:$PGID
    volumes:
      - $DOCKERDIR/appdata/maintainerr:/opt/data
    environment:
      TZ: $TZ
      DEBUG: true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.maintainerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.maintainerr-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.maintainerr-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.maintainerr-rtr.service=maintainerr-svc"
      - "traefik.http.services.maintainerr-svc.loadbalancer.server.port=6246"