services:
  # Resilio Sync - File Sync using BitTorrent Protocol
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["apps", "all"]
    networks:
      - t3_proxy
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - $DOCKERDIR/appdata/resilio-sync/config:/config
      - $DOWNLOADSDIR:/downloads 
      - $DOCKERDIR/appdata/resilio-sync/data:/sync # Change $DOCKERDIR/appdata/resilio-sync/data to your data folder
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.resilio-sync-rtr.entrypoints=websecure"
      - "traefik.http.routers.resilio-sync-rtr.rule=Host(`SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1`)"
      ## Middlewares
      - "traefik.http.routers.resilio-sync-rtr.middlewares=CHAIN-PLACEHOLDER@file"
      ## HTTP Services
      - "traefik.http.routers.resilio-sync-rtr.service=resilio-sync-svc"
      - "traefik.http.services.resilio-sync-svc.loadbalancer.server.port=8888"